<template>
  <div>

    <div class="container">
      <div class="jumbotron container-fluid">
          <h1 class="display-3">Custom Weather App</h1>
          <p class="lead">Personalized Weather App</p>
          <hr class="my-4">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur velit id felis dictum, sed hendrerit lorem faucibus. In molestie nibh ante, vel molestie nibh posuere ac. Phasellus a lectus commodo, ornare mauris sit amet, vestibulum ante. Suspendisse vitae sollicitudin felis. Etiam lacinia ligula sed eros maximus tempus. Etiam vestibulum malesuada massa, et rhoncus nulla ullamcorper quis. Praesent leo ipsum, finibus quis condimentum quis, efficitur et dui. Etiam sapien ante, auctor at leo at, rhoncus imperdiet turpis.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget sapien sed ante dapibus ultrices a eu augue. Morbi et nunc quis nibh gravida pulvinar non sit amet elit. Aenean ut volutpat augue, a blandit urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin at tellus tempus, lobortis purus in, dignissim ligula. Sed tristique velit lorem, ac rutrum tortor egestas at. Nulla non erat id quam vestibulum tristique sit amet vehicula odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus pulvinar interdum nunc nec tempor. Fusce sapien urna, mollis in dolor a, mattis egestas metus. Suspendisse potenti.</p>

          <p>
            Mauris ultrices elit eget lectus interdum, non maximus magna vestibulum. Maecenas nec velit non ante ultrices convallis. Duis eu sapien dictum, venenatis nunc eu, interdum odio. Vestibulum hendrerit nisi at elit venenatis, sed efficitur eros tincidunt. Donec eleifend tincidunt mi, ut consequat erat vestibulum id. Sed sit amet purus eu nibh tincidunt varius et vitae lorem. Maecenas justo erat, faucibus vitae metus vel, consequat ultrices neque. Etiam a imperdiet leo, nec sagittis ex. Integer mi felis, finibus et eleifend at, feugiat rhoncus sapien. Curabitur imperdiet, tellus sit amet tempor tristique, turpis tortor ultricies risus, in euismod magna enim non ex.
          </p>

          <p class="lead">

                <router-link class="btn btn-primary btn-lg" to="/about"><a>Read More</a> </router-link>

          </p>
      </div>
    </div>

  </div>
</template>

<script>


</script>

<style>

</style>
